name: 4 Build RTD Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'doc/**'
      - '.readthedocs.yaml'

  workflow_dispatch:

jobs:
  trigger-rtd:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Read the Docs build
        run: |
          curl -X POST "${{ secrets.RTD_BUILD_URL }}"
